// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Page(arg1, arg2) {
  return window['go']['openAPI']['OpenAPI']['Page'](arg1, arg2);
}

export function Save(arg1) {
  return window['go']['openAPI']['OpenAPI']['Save'](arg1);
}
