// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDatabaseConfig(arg1) {
  return window['go']['openAPI']['OpenAPI']['DeleteDatabaseConfig'](arg1);
}

export function Page(arg1, arg2) {
  return window['go']['openAPI']['OpenAPI']['Page'](arg1, arg2);
}

export function SaveDatabaseConfig(arg1) {
  return window['go']['openAPI']['OpenAPI']['SaveDatabaseConfig'](arg1);
}

export function TestConnect(arg1) {
  return window['go']['openAPI']['OpenAPI']['TestConnect'](arg1);
}
