// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function Page(arg1:number,arg2:number):Promise<entity.PageInfo>;

export function Save(arg1:entity.DatabaseConfig):Promise<void>;
